language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
addons:
  apt_packages:
    - pandoc
before_install:
  - chmod +x gradlew
  - sudo apt-get install ant
install:
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"
  - echo y | sdkmanager "ndk-bundle;16"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  # scripts excutes inside our repo directory on CI machine
  - export SAMPLE_CI_RESULT=0
  - source .ci_tools/setup_env.sh
  - source .ci_tools/build_samples.sh
  - source .ci_tools/run_samples.sh
  - source .ci_tools/misc_ci.sh
  - eval "[[ $SAMPLE_CI_RESULT == 0 ]]"
  - ./gradlew assembleRelease

after_success:
  - ./gradlew bintrayUpload -PbintrayUser=$BINTRAYUSER -PbintrayKey=$BINTRAYKEY  --info