language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
addons:
  apt_packages:
    - pandoc
before_install:
  - chmod +x gradlew
  - sudo apt-get install ant
install:
  - echo y | sdkmanager "ndk-bundle;16.1.4479499"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - ./gradlew assembleRelease

after_success:
  - ./gradlew bintrayUpload -PbintrayUser=$BINTRAYUSER -PbintrayKey=$BINTRAYKEY  --info